name: todolistapp

version: "3.8"

services:
  # MySQL Database Service
  mysql:
    image: mysql:8.0
    container_name: todolist_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todolist_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend Service
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: todolist_backend
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - DB_SERVER=mysql
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=3306
      - JWT_KEY=${JWT_KEY}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_EXPIRATION_HOURS=${JWT_EXPIRATION_HOURS}
      - AUTO_MIGRATE=${AUTO_MIGRATE}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - todolist_network

  # Frontend Service (với Nginx tích hợp)
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
      args:
        - VITE_BE_URL=${VITE_BE_URL}
    container_name: todolist_frontend
    ports:
      - "5368:80" # Export port ra ngoài
    depends_on:
      - backend
    networks:
      - todolist_network
    restart: unless-stopped

volumes:
  mysql_data:
    name: todolistapp_mysql_data

networks:
  todolist_network:
    name: todolistapp_network
    driver: bridge
